### ISSUE TITLE
Connect Cesium with our own backend server

### ISSUE THREAD

**Issue by shrew97** [Wire-Flies/MVK-SAAB#12]
The current frontend version is running on the server supplied by the cesium package (it's a huge mess of random files no human can simply comprehend), I'm going to need some help integrating this with the server our backend team put together and/or just removing files that are not necessary from the current Cesium project. Not sure what requirements Cesium has on the server, not very experienced when it comes to that. Soooo, gonna need some help ;_;

Another option is to have the "cesium part" of our project run on its own and not be in contact with the server that we currently have? Not sure what the optimal solution is, please discuss :3 

Cesium seems to work very well with Webpack btw, never used it before though but maybe one of you have. So whatever server we’re gonna connect our Cesium frontend to (its own server or to the server that the backend team has built), Webpack should be considered as a core module I feel unless we find anything else. It’s something we need to discuss atleast! :D

Uhh.. noterade att jag skrev på engelska. Stelt.

**Comment by jvikstrom** [comment]
We should probably just run the cesium server in its own process. That's probably the simplest way to integrate everything

**Comment by shrew97** [comment]
I agree, that might be the best way to go about at this moment. We can simply use the server that Cesium comes with, should be viable enough.

**Comment by shrew97** [comment]
Since we came to the conclusion that we're gonna run the Cesium server in its own process I'm closing this issue because it's no longer relevant.
