### ISSUE TITLE
Create cesium frontend that listens to the firebase database

### ISSUE THREAD

**Issue by jvikstrom** [Wire-Flies/MVK-SAAB#7]
Wrap cesium in react

**Comment by shrew97** [comment]
Fungerar nu (ligger i cesium_frontend branchen), men det du skrev om att wrap'a cesium i React är ännu oklart huruvida om vi ska göra det. Verkar ganska struligt att kombinera React och Cesium, men vi borde försöka diskutera oss fram till hur programmet bör se ut när det väl används. Ifall det enbart ska t.ex. vara Cesiumkartan som syns eller man ska ha en sida med flertal features där Cesiumkartan är en av dem osv. Huruvida vi ska kombinera Cesium med något finner jag är upp till hur programmet är tänkt att användas, standalone, hemsida etc. Stänger denna issue'n eftersom att den är uppfylld, men vi bör diskutera hur programmet faktiskt ska vara, då öppnar vi en ny issue för det.
