### ISSUE TITLE
Display firebase anomalies in the cesium frontend

### ISSUE THREAD

**Issue by jvikstrom** [Wire-Flies/MVK-SAAB#8]

**Comment by shrew97** [comment]
Borde fungera nu, clone'a gärna hem cesium_frontend branchen och testa dem som vill! För att starta servern:
node server.js
Sen gå till:
http://localhost:8080/Apps/HelloWorld.html

Här är en bild hur det ser ut i nuläget i alla fall för er som inte har ork att clone'a repot:

![6f03f2a9f7bb6d5ae3e55ce41d29cbdd](https://user-images.githubusercontent.com/22689212/35949813-b77b302e-0c73-11e8-81b2-8b3c98300caa.jpg)

Det som saknas i nuläget är rotationen för planen samt att begränsa hur mycket kameran kan zooma, annars fungerar det mesta på den fronten. Vad mer skulle ni vilja se utifrån entiteter, kameran, kartan osv?

**Comment by shrew97** [comment]
Såhär ser det ut just nu:

![e084dd4fc8a9d28e64ca3a248596826f](https://user-images.githubusercontent.com/22689212/36005108-46b7be8e-0d36-11e8-8970-2cf4cc480940.jpg)

Rotation fungerar dessutom nu samt att ifall något värde ändras i databasen kommer entiteten att uppdateras i Cesium i realtid. 
Eftersom att vi nu lyckats visa anomalier i realtid så anser jag att denna issue'n kan stängas 👍

**Comment by simake** [comment]
Wow, sweet!
